const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={tasks:[{id:1,name:'Finish project brief',time:'10:00 AM · Work',tag:'WORK',done:true},{id:2,name:'30 minute strength workout',time:'7:00 AM · Health',tag:'HEALTH',done:true},{id:3,name:'Reply to client emails',time:'11:30 AM · Work',tag:'WORK',done:false},{id:4,name:'Plan tomorrow’s top three',time:'5:30 PM · Personal',tag:'PERSONAL',done:false},{id:5,name:'Read for 20 minutes',time:'9:30 PM · Personal',tag:'PERSONAL',done:false}],habits:[{id:1,name:'Morning movement',sub:'12 day streak',icon:'☀',checked:true},{id:2,name:'Read a little',sub:'8 day streak',icon:'⌁',checked:true},{id:3,name:'Drink water',sub:'Daily goal: 8 glasses',icon:'◌',checked:false},{id:4,name:'No phone before bed',sub:'4 day streak',icon:'☾',checked:false}],expenses:[],events:[],journal:'',remindersEnabled:false,monthlyBudget:0,focusDuration:25,focusHistory:{}};
let data=JSON.parse(localStorage.getItem('daylight-data')||'null')||defaults; data.events??=[];data.remindersEnabled??=false;data.monthlyBudget??=0;data.focusDuration??=25;data.focusHistory??={};data.expenses=(data.expenses||[]).filter(expense=>expense.date||!['Lunch at Green Bowl','Metro card top-up','Cold brew'].includes(expense.name));
function localDayKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function prepareHabitsForToday(){let today=localDayKey();data.habits??=[];data.habits.forEach(habit=>{habit.history??={};if(habit.checked&&Object.keys(habit.history).length===0)habit.history[today]=true;habit.checked=habit.history[today]===true})}
prepareHabitsForToday();
const themeStorageKey='daylight-theme';
function hasNativeReminders(){return Boolean(window.AndroidNative&&typeof window.AndroidNative.syncReminders==='function')}
function applyTheme(theme){let dark=theme==='dark';document.body.classList.toggle('dark',dark);$('#themeBtn').textContent=dark?'☀':'☾';document.querySelector('meta[name="theme-color"]').content=dark?'#171624':'#faf9f6';if(window.AndroidNative?.setSystemBars)AndroidNative.setSystemBars(dark);localStorage.setItem(themeStorageKey,theme)}
let calDate=new Date(),timer=(Number(data.focusDuration)||25)*60,timerRunning=false,timerTick,action='task',plannerFilter='today';
const supabaseReady=Boolean(window.DAYLIGHT_SUPABASE_URL&&window.DAYLIGHT_SUPABASE_KEY&&window.supabase);
const sb=supabaseReady?window.supabase.createClient(window.DAYLIGHT_SUPABASE_URL,window.DAYLIGHT_SUPABASE_KEY):null;
let currentUser=null,authMode='signin',lastCloudUpdate=0,cloudSyncBusy=false;
function normalizeData(saved){data={...defaults,...saved};data.events??=[];data.remindersEnabled??=false;data.monthlyBudget??=0;data.focusDuration=Math.min(180,Math.max(1,Number(data.focusDuration)||25));data.focusHistory??={};data.expenses=(data.expenses||[]).filter(expense=>expense.date||!['Lunch at Green Bowl','Metro card top-up','Cold brew'].includes(expense.name));prepareHabitsForToday()}
function persist(){localStorage.setItem('daylight-data',JSON.stringify(data));if(sb&&currentUser){let updatedAt=new Date().toISOString();lastCloudUpdate=Date.parse(updatedAt);sb.from('daylight_profiles').upsert({user_id:currentUser.id,data,updated_at:updatedAt}).then(({error})=>{if(error)console.error('Cloud save failed:',error.message)})}} function fmtDate(d){return d.toLocaleDateString('en-IN',{weekday:'long',month:'long',day:'numeric'})}
function refreshAll(){renderTasks();renderHabits();renderExpenses();renderCalendar();renderTimer();renderGreeting();updateReminderButton();scheduleReminders()}
function renderGreeting(){let hour=new Date().getHours(),greeting=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening',quotes=[['“The secret of getting ahead is getting started.”','— Mark Twain'],['“Great things are done by a series of small things.”','— Vincent van Gogh'],['“Action is the foundational key to all success.”','— Pablo Picasso'],['“You do not have to see the whole staircase.”','— Martin Luther King Jr.'],['“The future depends on what you do today.”','— Mahatma Gandhi']],day=Math.floor(Date.now()/86400000),quote=quotes[day%quotes.length];$('#greetingText').textContent=greeting;$('#dailyQuote').innerHTML=`${quote[0]}<small>${quote[1]}</small>`}
function profileNameFor(user){let emailName=user.email.split('@')[0],saved=data.profileName?.trim(),accountName=user.user_metadata?.name?.trim();return accountName&&(!saved||saved===emailName)?accountName:(saved||accountName||emailName)}
function needsProfileName(user){let emailName=user.email.split('@')[0],saved=data.profileName?.trim(),accountName=user.user_metadata?.name?.trim();return !accountName&&(!saved||saved===emailName)}
function updateProfileLabels(name){$('#userName').textContent=name;$('#dashboardName').textContent=`${name}.`;$('#userAvatar').textContent=name[0].toUpperCase()}
function showApp(user){$('#authScreen').hidden=true;$('.app-shell').hidden=false;currentUser=user;let name=profileNameFor(user);data.profileName=name;updateProfileLabels(name);$('#userEmail').textContent=user.email;$('#signOutBtn').hidden=false;if(needsProfileName(user))setTimeout(()=>{$('#profileName').value='';$('#profileDialog').showModal();$('#profileName').focus()},0)}
async function loadUserData(user){currentUser=user;let {data:row,error}=await sb.from('daylight_profiles').select('data,updated_at').eq('user_id',user.id).maybeSingle();if(error){console.error(error.message);return}if(row?.data){normalizeData(row.data);lastCloudUpdate=Date.parse(row.updated_at)||0}else{normalizeData(defaults);persist()}data.profileName=profileNameFor(user);persist();showApp(user);refreshAll();startCloudSync()}
async function syncFromCloud(){if(!sb||!currentUser||cloudSyncBusy)return;cloudSyncBusy=true;let {data:row,error}=await sb.from('daylight_profiles').select('data,updated_at').eq('user_id',currentUser.id).maybeSingle();cloudSyncBusy=false;if(error||!row?.data)return;let remoteTime=Date.parse(row.updated_at)||0;if(remoteTime>lastCloudUpdate){normalizeData(row.data);lastCloudUpdate=remoteTime;data.profileName=profileNameFor(currentUser);localStorage.setItem('daylight-data',JSON.stringify(data));refreshAll()}}
function startCloudSync(){clearInterval(window.daylightCloudSync);window.daylightCloudSync=setInterval(syncFromCloud,5000)}
async function setSession(user){await loadUserData(user)}
async function initializeAuth(){if(!sb)return;$('.app-shell').hidden=true;$('#authScreen').hidden=false;let {data:{session}}=await sb.auth.getSession();if(session)await setSession(session.user)}
async function submitAuth(e){e.preventDefault();let email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim(),message=$('#authMessage'),button=$('#authSubmit');button.disabled=true;message.textContent='';let result=authMode==='signin'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{data:{name:name||email.split('@')[0]}}});button.disabled=false;if(result.error){message.textContent=result.error.message;return}if(authMode==='signup'&&!result.data.session){message.textContent='Account created. Check your email to confirm, then sign in.';message.className='auth-message success';return}await setSession(result.data.user)}
function notify(title,body){if(!data.remindersEnabled)return;if(hasNativeReminders())return AndroidNative.showNotification(title,body);if(Notification.permission==='granted')new Notification(title,{body,icon:'icon.svg'})}
function nextHabitOccurrence(value){let source=new Date(value),next=new Date();next.setHours(source.getHours(),source.getMinutes(),0,0);if(next<=new Date())next.setDate(next.getDate()+1);return `${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}-${String(next.getDate()).padStart(2,'0')}T${String(next.getHours()).padStart(2,'0')}:${String(next.getMinutes()).padStart(2,'0')}`}
function scheduleReminders(){let items=[...data.tasks.filter(x=>x.notify&&x.scheduledAt&&!x.done).map(x=>({...x,type:'Task'})),...data.habits.filter(x=>x.notify&&x.scheduledAt).map(x=>({...x,scheduledAt:nextHabitOccurrence(x.scheduledAt),type:'Habit',repeatDaily:true})),...data.events.filter(x=>x.notify&&x.scheduledAt).map(x=>({...x,type:'Calendar event'}))].filter(x=>new Date(x.scheduledAt)>new Date()).sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt));if(hasNativeReminders()){if(items.length)AndroidNative.requestExactAlarmPermissionIfNeeded();AndroidNative.syncReminders(JSON.stringify(items.map(x=>({id:`${x.type}-${x.id}`,title:`${x.type}: ${x.name}`,body:x.type==='Habit'?'Time for your daily habit check-in.':'It’s time for your scheduled reminder.',scheduledAt:x.scheduledAt,repeatDaily:Boolean(x.repeatDaily)}))));return}clearTimeout(window.reminderTimer);if(!items.length)return;let next=items[0],delay=Math.min(new Date(next.scheduledAt)-Date.now(),2147483647);window.reminderTimer=setTimeout(()=>{notify(`${next.type}: ${next.name}`,'It’s time for your scheduled reminder.');scheduleReminders()},delay)}
async function enableReminders(){if(hasNativeReminders()){AndroidNative.requestNotificationPermission();return}if(!('Notification'in window))return alert('Notifications are not supported in this browser.');let p=Notification.permission==='default'?await Notification.requestPermission():Notification.permission;data.remindersEnabled=p==='granted';persist();updateReminderButton();if(data.remindersEnabled)scheduleReminders();else alert('Notifications are blocked. Enable them in browser settings to receive reminders.')}
function updateReminderButton(){$('#notificationLabel').textContent=data.remindersEnabled?'Reminders on':'Reminders off'}
function renderTasks(){let done=data.tasks.filter(t=>t.done).length,remain=data.tasks.length-done;$('#tasksDoneStat').innerHTML=`${done} <em>/ ${data.tasks.length}</em>`;$('#remainingTasks').textContent=`${remain} remaining`;$('#navTaskCount').textContent=remain;$('#completionPercent').textContent=`${Math.round(done/data.tasks.length*100)}%`;$('#completedLong').textContent=`${done} tasks`;let card=t=>`<div class="task ${t.done?'done':''}"><input type="checkbox" aria-label="Complete ${t.name}" data-task="${t.id}" ${t.done?'checked':''}><p><strong>${t.name}</strong><small>${t.scheduledAt?new Date(t.scheduledAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):t.time}${t.notify?' · reminder on':''}</small></p><span class="tag ${t.tag==='WORK'?'work':t.tag==='HEALTH'?'health':''}">${t.tag}</span><button class="remove-btn" data-remove-task="${t.id}" aria-label="Remove ${t.name}" title="Remove task">×</button></div>`;$('#todayTasks').innerHTML=data.tasks.slice(0,4).map(card).join('');$('#plannerTasks').innerHTML=data.tasks.map(card).join('');$$('[data-task]').forEach(e=>e.onchange=()=>{let t=data.tasks.find(x=>x.id==e.dataset.task);t.done=e.checked;persist();renderTasks();scheduleReminders()});$$('[data-remove-task]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this task?'))return;data.tasks=data.tasks.filter(t=>t.id!=b.dataset.removeTask);persist();renderTasks();scheduleReminders()})}
function renderHabits(){let c=data.habits.filter(h=>h.checked).length;$('#habitSummary').textContent=`${c} of ${data.habits.length} complete`;$('#streakStat').innerHTML=`${12+c} <em>days</em>`;let row=h=>`<div class="habit-row"><span class="habit-icon ${h.id%2?'':'lav'}">${h.icon}</span><p>${h.name}<small>${h.sub}</small></p><button class="habit-check ${h.checked?'checked':''}" data-habit="${h.id}" aria-label="Check in ${h.name}">${h.checked?'✓':''}</button><button class="remove-btn" data-remove-habit="${h.id}" aria-label="Remove ${h.name}" title="Remove habit">×</button></div>`;$('#habitList').innerHTML=data.habits.map(row).join('');$('#habitDots').innerHTML=data.habits.map(h=>`<i class="${h.checked?'active':''}"></i>`).join('');$('#habitsPage').innerHTML=data.habits.map(h=>`<article class="panel habit-card"><button class="remove-btn" data-remove-habit="${h.id}" aria-label="Remove ${h.name}" title="Remove habit">×</button><span class="habit-icon">${h.icon}</span><h2>${h.name}</h2><p class="muted">${h.sub}</p><div class="week-track">${['M','T','W','T','F','S','S'].map((d,i)=>`<div>${d}<i class="${h.checked||i<3?'good':''}"></i></div>`).join('')}</div></article>`).join('');$$('[data-habit]').forEach(e=>e.onclick=()=>{let h=data.habits.find(x=>x.id==e.dataset.habit);h.checked=!h.checked;persist();renderHabits()});$$('[data-remove-habit]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this habit?'))return;data.habits=data.habits.filter(h=>h.id!=b.dataset.removeHabit);persist();renderHabits()})}
function renderExpenses(){let total=data.expenses.reduce((a,e)=>a+e.amount,0);$('#spentStat').textContent=`₹${total}`;$('#monthSpend').textContent=`₹${(3420+total).toLocaleString('en-IN')}`;$('#budgetBar').style.width=`${Math.min(100,Math.round((3420+total)/120))}%`;$('#expenseList').innerHTML=data.expenses.map(e=>`<div class="expense"><span class="expense-icon">${e.icon}</span><p>${e.name}<small>${e.cat} · Today</small></p><strong>− ₹${e.amount}</strong></div>`).join('');let cats={};data.expenses.forEach(e=>cats[e.cat]=(cats[e.cat]||0)+e.amount);$('#categoryBars').innerHTML=Object.entries(cats).map(([n,v])=>`<div><span>${n}</span><i style="--width:${Math.min(100,v/3)}%"></i><b>₹${v}</b></div>`).join('')}
function renderCalendar(){let y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate(),today=new Date();$('#monthTitle').textContent=calDate.toLocaleDateString('en-IN',{month:'long',year:'numeric'});let html='';for(let i=0;i<42;i++){let n=i-first+1,other=n<1||n>days;if(n<1)n=prev+n;if(n>days)n-=days;let active=!other&&today.getFullYear()==y&&today.getMonth()==m&&today.getDate()==n;let has=data.events.some(e=>{let d=new Date(e.scheduledAt);return d.getFullYear()===y&&d.getMonth()===m&&d.getDate()===n});html+=`<div class="day ${other?'other':''} ${active?'today':''}"><span class="date-number">${n}</span>${has?'<i class="event-dot"></i>':''}</div>`}$('#calendarGrid').innerHTML=html;let events=data.events.filter(e=>{let d=new Date(e.scheduledAt);return d.getFullYear()===y&&d.getMonth()===m}).sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt));$('#calendarEvents').innerHTML=events.length?events.map(e=>`<article class="panel calendar-event"><time>${new Date(e.scheduledAt).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</time><p><strong>${e.name}</strong><small>${new Date(e.scheduledAt).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}${e.notify?' · reminder on':''}</small></p></article>`).join(''):'<p class="muted">No events scheduled for this month.</p>'}
function focusSeconds(){return Math.max(60,Number(data.focusDuration||25)*60)}
function focusSessionsToday(){return Number(data.focusHistory?.[localDayKey()]||0)}
function renderTimer(){let m=Math.floor(timer/60),s=timer%60;$('#timerValue').textContent=`${m}:${String(s).padStart(2,'0')}`;$('#timerProgress').style.strokeDashoffset=421*(1-timer/focusSeconds());$('#timerToggle').innerHTML=timerRunning?'❚❚ Pause':'▶ Start focus';$('#timerMode').textContent=`${data.focusDuration} min⌄`;$('#focusStat').innerHTML=`${focusSessionsToday()} <em>sessions</em>`}
function nextHabitReminder(time){let [hours,minutes]=time.split(':').map(Number),date=new Date();date.setHours(hours,minutes,0,0);if(date<=new Date())date.setDate(date.getDate()+1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}T${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`}
function openDialog(kind){action=kind;let titles={task:'Add a task',habit:'Create a habit',expense:'Add an expense',event:'Add calendar event',budget:'Set monthly limit'};$('#dialogTitle').textContent=titles[kind];$('#entryName').value=kind==='budget'?'Monthly spending limit':'';$('#entryExtra').value=kind==='budget'?(data.monthlyBudget||''):'';$('#entrySchedule').value=kind==='expense'?new Date().toISOString().slice(0,10):'';$('#entryNotify').checked=false;let scheduled=['task','event','habit'].includes(kind),isExpense=kind==='expense';$('#scheduleLabel').style.display=(scheduled||isExpense)?'block':'none';$('#notifyLabel').style.display=scheduled?'flex':'none';$('.form-note').style.display=scheduled?'block':'none';$('#entrySchedule').type=kind==='habit'?'time':isExpense?'date':'datetime-local';$('#scheduleLabel').firstChild.textContent=kind==='habit'?'Reminder time ':isExpense?'Expense date ':'Schedule (optional)';$('#entryExtraLabel').style.display=kind==='budget'?'block':'block';$('#entryExtraLabel').firstChild.textContent=kind==='task'?'Time ':kind==='habit'?'Goal / note ':kind==='expense'||kind==='budget'?'Amount (₹) ':'Notes ';$('#entryExtra').placeholder=kind==='task'?'e.g. 10:00 AM':kind==='habit'?'e.g. Daily':kind==='expense'||kind==='budget'?'e.g. 12000':'Optional';$('#entryDialog').showModal();$('#entryName').focus()}
function changeView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('.sidebar').classList.remove('open');window.scrollTo(0,0)}
window.addEventListener('native-notification-permission',event=>{data.remindersEnabled=Boolean(event.detail);persist();updateReminderButton();if(data.remindersEnabled)scheduleReminders();else alert('Notifications are blocked. Enable notifications in the Android app settings to receive reminders.')});
if(hasNativeReminders())data.remindersEnabled=AndroidNative.areNotificationsEnabled();
applyTheme(localStorage.getItem(themeStorageKey)||'light');
$('#todayLabel').textContent=fmtDate(new Date());$('#journalDate').textContent=fmtDate(new Date());$('#journalText').value=data.journal;refreshAll();
$$('.nav-item').forEach(b=>b.onclick=()=>changeView(b.dataset.view));$$('[data-view-link]').forEach(b=>b.onclick=()=>changeView(b.dataset.viewLink));$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$('#quickAdd').onclick=()=>openDialog('task');$('#addTaskBtn').onclick=()=>openDialog('task');$('#plannerAdd').onclick=()=>openDialog('task');$('#addHabit').onclick=()=>openDialog('habit');$('#addExpense').onclick=()=>openDialog('expense');$('#addEvent').onclick=()=>openDialog('event');$('#setBudgetBtn').onclick=()=>openDialog('budget');$('#notificationBtn').onclick=enableReminders;$('#dialogClose').onclick=()=>$('#entryDialog').close();
$('#entryForm').addEventListener('submit',e=>{e.preventDefault();let name=$('#entryName').value.trim(),extra=$('#entryExtra').value.trim(),scheduleValue=$('#entrySchedule').value,notifyAt=$('#entryNotify').checked,scheduledAt=action==='habit'&&scheduleValue?nextHabitReminder(scheduleValue):scheduleValue;if(!name)return;if((notifyAt||action==='event')&&!scheduledAt){alert('Choose a scheduled date and time before saving.');return}if(notifyAt&&!data.remindersEnabled)enableReminders();if(action==='task')data.tasks.push({id:Date.now(),name,time:extra||'Anytime · Personal',tag:'PERSONAL',done:false,scheduledAt,notify:notifyAt,createdAt:new Date().toISOString()});if(action==='habit')data.habits.push({id:Date.now(),name,sub:extra||'Start your streak',icon:'✦',checked:false,scheduledAt,notify:notifyAt});if(action==='expense')data.expenses.unshift({id:Date.now(),name,cat:'Other',amount:Number(extra)||0,icon:'◈',date:scheduleValue?`${scheduleValue}T12:00:00`:new Date().toISOString()});if(action==='event')data.events.push({id:Date.now(),name,notes:extra,scheduledAt,notify:notifyAt});if(action==='budget')data.monthlyBudget=Math.max(0,Number(extra)||0);persist();refreshAll();$('#entryDialog').close()});
$('#prevMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};$('#goToday').onclick=()=>{calDate=new Date();renderCalendar()};$('#timerToggle').onclick=()=>{timerRunning=!timerRunning;if(timerRunning)timerTick=setInterval(()=>{if(timer>0){timer--;renderTimer()}else{clearInterval(timerTick);timerRunning=false;data.focusHistory[localDayKey()]=focusSessionsToday()+1;timer=focusSeconds();persist();notify('Focus session complete','Nice work. Take a gentle break.');renderTimer()}},1000);else clearInterval(timerTick);renderTimer()};$('#timerReset').onclick=()=>{timer=focusSeconds();timerRunning=false;clearInterval(timerTick);renderTimer()};$('#timerMode').onclick=()=>{$('#focusDuration').value=data.focusDuration;$('#focusDialog').showModal();$('#focusDuration').focus()};$('#focusDialogClose').onclick=()=>$('#focusDialog').close();$('#focusForm').onsubmit=e=>{e.preventDefault();let minutes=Math.min(180,Math.max(1,Number($('#focusDuration').value)||25));data.focusDuration=minutes;timer=focusSeconds();timerRunning=false;clearInterval(timerTick);persist();renderTimer();$('#focusDialog').close()};
$('#saveJournal').onclick=()=>{data.journal=$('#journalText').value;persist();$('#saveStatus').textContent='Saved just now';setTimeout(()=>$('#saveStatus').textContent='',2400)};$('#themeBtn').onclick=()=>applyTheme(document.body.classList.contains('dark')?'light':'dark');$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='daylight-backup.json';a.click()};
$('#authForm').onsubmit=submitAuth;$('#authSwitch').onclick=()=>{authMode=authMode==='signin'?'signup':'signin';let signingUp=authMode==='signup';$('#authNameLabel').hidden=!signingUp;$('#authName').required=signingUp;$('#authPassword').autocomplete=signingUp?'new-password':'current-password';$('#authSubmit').textContent=signingUp?'Create account':'Sign in';$('#authSwitch').textContent=signingUp?'Already have an account? Sign in':'New here? Create a free account';$('#authMessage').textContent=''};$('#signOutBtn').onclick=async()=>{await sb.auth.signOut();currentUser=null;$('.app-shell').hidden=true;$('#authScreen').hidden=false};initializeAuth();
$('#profileForm').onsubmit=async e=>{e.preventDefault();let name=$('#profileName').value.trim();if(name.length<2)return;data.profileName=name;persist();updateProfileLabels(name);$('#profileDialog').close();if(sb&&currentUser){let {error}=await sb.auth.updateUser({data:{name}});if(error)console.error('Profile name update failed:',error.message)}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});

// Planner filters and live finance data are kept here so old saved data continues to work.
function dateIsToday(value){if(!value)return true;let d=new Date(value),now=new Date();return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()&&d.getDate()===now.getDate()}
function dateIsThisWeek(value){if(!value)return true;let d=new Date(value),now=new Date(),start=new Date(now);start.setHours(0,0,0,0);start.setDate(now.getDate()-now.getDay());let end=new Date(start);end.setDate(start.getDate()+7);return d>=start&&d<end}
function plannerTaskCard(t){return `<div class="task ${t.done?'done':''}"><input type="checkbox" aria-label="Complete ${t.name}" data-planner-task="${t.id}" ${t.done?'checked':''}><p><strong>${t.name}</strong><small>${t.scheduledAt?new Date(t.scheduledAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):t.time}${t.notify?' · reminder on':''}</small></p><span class="tag ${t.tag==='WORK'?'work':t.tag==='HEALTH'?'health':''}">${t.tag}</span><button class="remove-btn" data-planner-remove="${t.id}" aria-label="Remove ${t.name}" title="Remove task">×</button></div>`}
function renderPlanner(){let filtered=data.tasks.filter(t=>plannerFilter==='all'||(plannerFilter==='today'?dateIsToday(t.scheduledAt):dateIsThisWeek(t.scheduledAt)));$('#plannerTasks').innerHTML=filtered.length?filtered.map(plannerTaskCard).join(''):'<p class="muted empty-state">No tasks in this view yet.</p>';$$('[data-task-filter]').forEach(b=>b.classList.toggle('selected',b.dataset.taskFilter===plannerFilter));$$('[data-planner-task]').forEach(e=>e.onchange=()=>{let task=data.tasks.find(t=>t.id==e.dataset.plannerTask);task.done=e.checked;persist();refreshAll()});$$('[data-planner-remove]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this task?'))return;data.tasks=data.tasks.filter(t=>t.id!=b.dataset.plannerRemove);persist();refreshAll()})}
$$('[data-task-filter]').forEach(button=>button.onclick=()=>{plannerFilter=button.dataset.taskFilter;renderPlanner()});
function renderExpenses(){let today=new Date(),sameMonth=e=>{let d=new Date(e.date||today);return d.getFullYear()===today.getFullYear()&&d.getMonth()===today.getMonth()},month=data.expenses.filter(sameMonth),total=month.reduce((sum,e)=>sum+Number(e.amount||0),0),todayTotal=data.expenses.filter(e=>dateIsToday(e.date)).reduce((sum,e)=>sum+Number(e.amount||0),0),budget=Number(data.monthlyBudget)||0;$('#spentStat').textContent=`₹${todayTotal.toLocaleString('en-IN')}`;$('#monthSpend').textContent=`₹${total.toLocaleString('en-IN')}`;$('#budgetLabel').textContent=budget?`of ₹${budget.toLocaleString('en-IN')} monthly limit · ₹${Math.max(0,budget-total).toLocaleString('en-IN')} remaining`:'Set your monthly limit to track your progress.';$('#budgetBar').style.width=budget?`${Math.min(100,Math.round(total/budget*100))}%`:'0%';$('#expenseList').innerHTML=month.length?month.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,8).map(e=>`<div class="expense"><span class="expense-icon">${e.icon||'◈'}</span><p>${e.name}<small>${e.cat||'Other'} · ${e.date?new Date(e.date).toLocaleDateString('en-IN',{day:'numeric',month:'short'}):'This month'}</small></p><strong>− ₹${Number(e.amount||0).toLocaleString('en-IN')}</strong></div>`).join(''):'<p class="muted empty-state">No expenses recorded this month.</p>';let categories={};month.forEach(e=>categories[e.cat||'Other']=(categories[e.cat||'Other']||0)+Number(e.amount||0));$('#categoryBars').innerHTML=Object.entries(categories).length?Object.entries(categories).map(([name,value])=>`<div><span>${name}</span><i style="--width:${Math.min(100,value/Math.max(total,1)*100)}%"></i><b>₹${value.toLocaleString('en-IN')}</b></div>`).join(''):'<p class="muted empty-state">Add expenses to see monthly categories.</p>';let days=Array.from({length:7},(_,i)=>{let d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-6+i);return d}),values=days.map(d=>data.expenses.filter(e=>{let x=new Date(e.date||today);return x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth()&&x.getDate()===d.getDate()}).reduce((sum,e)=>sum+Number(e.amount||0),0)),max=Math.max(...values,1);$('#weekSpend').textContent=`₹${values.reduce((a,b)=>a+b,0).toLocaleString('en-IN')} this week`;$('#spendingChart').innerHTML=days.map((d,i)=>`<div class="bar-day ${i===6?'today':''}"><i style="height:${Math.max(4,values[i]/max*110)}px"></i><b>${d.toLocaleDateString('en-IN',{weekday:'short'})}</b></div>`).join('')}
let oldRefreshAll=refreshAll;refreshAll=()=>{oldRefreshAll();renderPlanner()};
