const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={tasks:[{id:1,name:'Finish project brief',time:'10:00 AM · Work',tag:'WORK',done:true},{id:2,name:'30 minute strength workout',time:'7:00 AM · Health',tag:'HEALTH',done:true},{id:3,name:'Reply to client emails',time:'11:30 AM · Work',tag:'WORK',done:false},{id:4,name:'Plan tomorrow’s top three',time:'5:30 PM · Personal',tag:'PERSONAL',done:false},{id:5,name:'Read for 20 minutes',time:'9:30 PM · Personal',tag:'PERSONAL',done:false}],habits:[{id:1,name:'Morning movement',sub:'12 day streak',icon:'☀',checked:true},{id:2,name:'Read a little',sub:'8 day streak',icon:'⌁',checked:true},{id:3,name:'Drink water',sub:'Daily goal: 8 glasses',icon:'◌',checked:false},{id:4,name:'No phone before bed',sub:'4 day streak',icon:'☾',checked:false}],expenses:[{id:1,name:'Lunch at Green Bowl',cat:'Food & dining',amount:280,icon:'🍜'},{id:2,name:'Metro card top-up',cat:'Transport',amount:100,icon:'◉'},{id:3,name:'Cold brew',cat:'Food & dining',amount:40,icon:'☕'}],events:[],journal:'',remindersEnabled:false};
let data=JSON.parse(localStorage.getItem('daylight-data')||'null')||defaults; data.events??=[];data.remindersEnabled??=false;
let calDate=new Date(),timer=1500,timerRunning=false,timerTick,action='task',plannerFilter='today';
const supabaseReady=Boolean(window.DAYLIGHT_SUPABASE_URL&&window.DAYLIGHT_SUPABASE_KEY&&window.supabase);
const sb=supabaseReady?window.supabase.createClient(window.DAYLIGHT_SUPABASE_URL,window.DAYLIGHT_SUPABASE_KEY):null;
let currentUser=null,authMode='signin';
function persist(){localStorage.setItem('daylight-data',JSON.stringify(data));if(sb&&currentUser)sb.from('daylight_profiles').upsert({user_id:currentUser.id,data,updated_at:new Date().toISOString()}).then(({error})=>{if(error)console.error('Cloud save failed:',error.message)})} function fmtDate(d){return d.toLocaleDateString('en-IN',{weekday:'long',month:'long',day:'numeric'})}
function refreshAll(){renderTasks();renderHabits();renderExpenses();renderCalendar();renderTimer();updateReminderButton();scheduleReminders()}
function showApp(user){$('#authScreen').hidden=true;$('.app-shell').hidden=false;currentUser=user;let name=data.profileName||user.user_metadata?.name||user.email.split('@')[0];$('#userName').textContent=name;$('#dashboardName').textContent=`${name}.`;$('#userEmail').textContent=user.email;$('#userAvatar').textContent=name[0].toUpperCase();$('#signOutBtn').hidden=false}
async function loadUserData(user){currentUser=user;let {data:row,error}=await sb.from('daylight_profiles').select('data').eq('user_id',user.id).maybeSingle();if(error){console.error(error.message);return}if(row?.data){data={...defaults,...row.data};data.events??=[];data.remindersEnabled??=false;data.profileName??=user.user_metadata?.name||user.email.split('@')[0]}else{data={...defaults,profileName:user.user_metadata?.name||user.email.split('@')[0]};persist()}showApp(user);refreshAll()}
async function setSession(user){await loadUserData(user)}
async function initializeAuth(){if(!sb)return;$('.app-shell').hidden=true;$('#authScreen').hidden=false;let {data:{session}}=await sb.auth.getSession();if(session)await setSession(session.user)}
async function submitAuth(e){e.preventDefault();let email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim(),message=$('#authMessage'),button=$('#authSubmit');button.disabled=true;message.textContent='';let result=authMode==='signin'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{data:{name:name||email.split('@')[0]}}});button.disabled=false;if(result.error){message.textContent=result.error.message;return}if(authMode==='signup'&&!result.data.session){message.textContent='Account created. Check your email to confirm, then sign in.';message.className='auth-message success';return}await setSession(result.data.user)}
function notify(title,body){if(data.remindersEnabled&&Notification.permission==='granted')new Notification(title,{body,icon:'icon.svg'})}
function scheduleReminders(){clearTimeout(window.reminderTimer);let items=[...data.tasks.filter(x=>x.notify&&x.scheduledAt&&!x.done).map(x=>({...x,type:'Task'})),...data.events.filter(x=>x.notify).map(x=>({...x,type:'Calendar event'}))].filter(x=>new Date(x.scheduledAt)>new Date()).sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt));if(!items.length)return;let next=items[0],delay=Math.min(new Date(next.scheduledAt)-Date.now(),2147483647);window.reminderTimer=setTimeout(()=>{notify(`${next.type}: ${next.name}`,'It’s time for your scheduled reminder.');scheduleReminders()},delay)}
async function enableReminders(){if(!('Notification'in window))return alert('Notifications are not supported in this browser.');let p=Notification.permission==='default'?await Notification.requestPermission():Notification.permission;data.remindersEnabled=p==='granted';persist();updateReminderButton();if(data.remindersEnabled)scheduleReminders();else alert('Notifications are blocked. Enable them in browser settings to receive reminders.')}
function updateReminderButton(){$('#notificationLabel').textContent=data.remindersEnabled?'Reminders on':'Reminders off'}
function renderTasks(){let done=data.tasks.filter(t=>t.done).length,remain=data.tasks.length-done;$('#tasksDoneStat').innerHTML=`${done} <em>/ ${data.tasks.length}</em>`;$('#remainingTasks').textContent=`${remain} remaining`;$('#navTaskCount').textContent=remain;$('#completionPercent').textContent=`${Math.round(done/data.tasks.length*100)}%`;$('#completedLong').textContent=`${done} tasks`;let card=t=>`<div class="task ${t.done?'done':''}"><input type="checkbox" aria-label="Complete ${t.name}" data-task="${t.id}" ${t.done?'checked':''}><p><strong>${t.name}</strong><small>${t.scheduledAt?new Date(t.scheduledAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):t.time}${t.notify?' · reminder on':''}</small></p><span class="tag ${t.tag==='WORK'?'work':t.tag==='HEALTH'?'health':''}">${t.tag}</span><button class="remove-btn" data-remove-task="${t.id}" aria-label="Remove ${t.name}" title="Remove task">×</button></div>`;$('#todayTasks').innerHTML=data.tasks.slice(0,4).map(card).join('');$('#plannerTasks').innerHTML=data.tasks.map(card).join('');$$('[data-task]').forEach(e=>e.onchange=()=>{let t=data.tasks.find(x=>x.id==e.dataset.task);t.done=e.checked;persist();renderTasks();scheduleReminders()});$$('[data-remove-task]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this task?'))return;data.tasks=data.tasks.filter(t=>t.id!=b.dataset.removeTask);persist();renderTasks();scheduleReminders()})}
function renderHabits(){let c=data.habits.filter(h=>h.checked).length;$('#habitSummary').textContent=`${c} of ${data.habits.length} complete`;$('#streakStat').innerHTML=`${12+c} <em>days</em>`;let row=h=>`<div class="habit-row"><span class="habit-icon ${h.id%2?'':'lav'}">${h.icon}</span><p>${h.name}<small>${h.sub}</small></p><button class="habit-check ${h.checked?'checked':''}" data-habit="${h.id}" aria-label="Check in ${h.name}">${h.checked?'✓':''}</button><button class="remove-btn" data-remove-habit="${h.id}" aria-label="Remove ${h.name}" title="Remove habit">×</button></div>`;$('#habitList').innerHTML=data.habits.map(row).join('');$('#habitDots').innerHTML=data.habits.map(h=>`<i class="${h.checked?'active':''}"></i>`).join('');$('#habitsPage').innerHTML=data.habits.map(h=>`<article class="panel habit-card"><button class="remove-btn" data-remove-habit="${h.id}" aria-label="Remove ${h.name}" title="Remove habit">×</button><span class="habit-icon">${h.icon}</span><h2>${h.name}</h2><p class="muted">${h.sub}</p><div class="week-track">${['M','T','W','T','F','S','S'].map((d,i)=>`<div>${d}<i class="${h.checked||i<3?'good':''}"></i></div>`).join('')}</div></article>`).join('');$$('[data-habit]').forEach(e=>e.onclick=()=>{let h=data.habits.find(x=>x.id==e.dataset.habit);h.checked=!h.checked;persist();renderHabits()});$$('[data-remove-habit]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this habit?'))return;data.habits=data.habits.filter(h=>h.id!=b.dataset.removeHabit);persist();renderHabits()})}
function renderExpenses(){let total=data.expenses.reduce((a,e)=>a+e.amount,0);$('#spentStat').textContent=`₹${total}`;$('#monthSpend').textContent=`₹${(3420+total).toLocaleString('en-IN')}`;$('#budgetBar').style.width=`${Math.min(100,Math.round((3420+total)/120))}%`;$('#expenseList').innerHTML=data.expenses.map(e=>`<div class="expense"><span class="expense-icon">${e.icon}</span><p>${e.name}<small>${e.cat} · Today</small></p><strong>− ₹${e.amount}</strong></div>`).join('');let cats={};data.expenses.forEach(e=>cats[e.cat]=(cats[e.cat]||0)+e.amount);$('#categoryBars').innerHTML=Object.entries(cats).map(([n,v])=>`<div><span>${n}</span><i style="--width:${Math.min(100,v/3)}%"></i><b>₹${v}</b></div>`).join('')}
function renderCalendar(){let y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate(),today=new Date();$('#monthTitle').textContent=calDate.toLocaleDateString('en-IN',{month:'long',year:'numeric'});let html='';for(let i=0;i<42;i++){let n=i-first+1,other=n<1||n>days;if(n<1)n=prev+n;if(n>days)n-=days;let active=!other&&today.getFullYear()==y&&today.getMonth()==m&&today.getDate()==n;let has=data.events.some(e=>{let d=new Date(e.scheduledAt);return d.getFullYear()===y&&d.getMonth()===m&&d.getDate()===n});html+=`<div class="day ${other?'other':''} ${active?'today':''}"><span class="date-number">${n}</span>${has?'<i class="event-dot"></i>':''}</div>`}$('#calendarGrid').innerHTML=html;let events=data.events.filter(e=>{let d=new Date(e.scheduledAt);return d.getFullYear()===y&&d.getMonth()===m}).sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt));$('#calendarEvents').innerHTML=events.length?events.map(e=>`<article class="panel calendar-event"><time>${new Date(e.scheduledAt).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</time><p><strong>${e.name}</strong><small>${new Date(e.scheduledAt).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}${e.notify?' · reminder on':''}</small></p></article>`).join(''):'<p class="muted">No events scheduled for this month.</p>'}
function renderTimer(){let m=Math.floor(timer/60),s=timer%60;$('#timerValue').textContent=`${m}:${String(s).padStart(2,'0')}`;$('#timerProgress').style.strokeDashoffset=421*(1-timer/1500);$('#timerToggle').innerHTML=timerRunning?'❚❚ Pause':'▶ Start focus'}
function openDialog(kind){action=kind;let titles={task:'Add a task',habit:'Create a habit',expense:'Add an expense',event:'Add calendar event'};$('#dialogTitle').textContent=titles[kind];$('#entryName').value='';$('#entryExtra').value='';$('#entrySchedule').value='';$('#entryNotify').checked=false;let scheduled=['task','event'].includes(kind);$('#scheduleLabel').style.display=scheduled?'block':'none';$('#notifyLabel').style.display=scheduled?'flex':'none';$('.form-note').style.display=scheduled?'block':'none';$('#entryExtraLabel').firstChild.textContent=kind==='task'?'Time ':kind==='habit'?'Goal / note ':kind==='expense'?'Amount (₹) ':'Notes ';$('#entryExtra').placeholder=kind==='task'?'e.g. 10:00 AM':kind==='habit'?'e.g. Daily':kind==='expense'?'e.g. 250':'Optional';$('#entryDialog').showModal();$('#entryName').focus()}
function changeView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('.sidebar').classList.remove('open');window.scrollTo(0,0)}
$('#todayLabel').textContent=fmtDate(new Date());$('#journalDate').textContent=fmtDate(new Date());$('#journalText').value=data.journal;refreshAll();
$$('.nav-item').forEach(b=>b.onclick=()=>changeView(b.dataset.view));$$('[data-view-link]').forEach(b=>b.onclick=()=>changeView(b.dataset.viewLink));$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$('#quickAdd').onclick=()=>openDialog('task');$('#addTaskBtn').onclick=()=>openDialog('task');$('#plannerAdd').onclick=()=>openDialog('task');$('#addHabit').onclick=()=>openDialog('habit');$('#addExpense').onclick=()=>openDialog('expense');$('#addEvent').onclick=()=>openDialog('event');$('#notificationBtn').onclick=enableReminders;$('#dialogClose').onclick=()=>$('#entryDialog').close();
$('#entryForm').addEventListener('submit',e=>{e.preventDefault();let name=$('#entryName').value.trim(),extra=$('#entryExtra').value.trim(),scheduledAt=$('#entrySchedule').value,notifyAt=$('#entryNotify').checked;if(!name)return;if((notifyAt||action==='event')&&!scheduledAt){alert('Choose a scheduled date and time before saving.');return}if(notifyAt&&!data.remindersEnabled)enableReminders();if(action==='task')data.tasks.push({id:Date.now(),name,time:extra||'Anytime · Personal',tag:'PERSONAL',done:false,scheduledAt,notify:notifyAt,createdAt:new Date().toISOString()});if(action==='habit')data.habits.push({id:Date.now(),name,sub:extra||'Start your streak',icon:'✦',checked:false});if(action==='expense')data.expenses.unshift({id:Date.now(),name,cat:'Other',amount:Number(extra)||0,icon:'◈',date:new Date().toISOString()});if(action==='event')data.events.push({id:Date.now(),name,notes:extra,scheduledAt,notify:notifyAt});persist();refreshAll();$('#entryDialog').close()});
$('#prevMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};$('#goToday').onclick=()=>{calDate=new Date();renderCalendar()};$('#timerToggle').onclick=()=>{timerRunning=!timerRunning;if(timerRunning)timerTick=setInterval(()=>{if(timer>0){timer--;renderTimer()}else{clearInterval(timerTick);timerRunning=false;notify('Focus session complete','Nice work. Take a gentle break.');renderTimer()}},1000);else clearInterval(timerTick);renderTimer()};$('#timerReset').onclick=()=>{timer=1500;timerRunning=false;clearInterval(timerTick);renderTimer()};$('#timerMode').onclick=()=>{timer=timer===1500?300:1500;renderTimer()};
$('#saveJournal').onclick=()=>{data.journal=$('#journalText').value;persist();$('#saveStatus').textContent='Saved just now';setTimeout(()=>$('#saveStatus').textContent='',2400)};$('#themeBtn').onclick=()=>document.body.classList.toggle('dark');$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='daylight-backup.json';a.click()};
$('#authForm').onsubmit=submitAuth;$('#authSwitch').onclick=()=>{authMode=authMode==='signin'?'signup':'signin';let signingUp=authMode==='signup';$('#authNameLabel').hidden=!signingUp;$('#authName').required=signingUp;$('#authPassword').autocomplete=signingUp?'new-password':'current-password';$('#authSubmit').textContent=signingUp?'Create account':'Sign in';$('#authSwitch').textContent=signingUp?'Already have an account? Sign in':'New here? Create a free account';$('#authMessage').textContent=''};$('#signOutBtn').onclick=async()=>{await sb.auth.signOut();currentUser=null;$('.app-shell').hidden=true;$('#authScreen').hidden=false};initializeAuth();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});

// Planner filters and live finance data are kept here so old saved data continues to work.
function dateIsToday(value){if(!value)return true;let d=new Date(value),now=new Date();return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()&&d.getDate()===now.getDate()}
function dateIsThisWeek(value){if(!value)return true;let d=new Date(value),now=new Date(),start=new Date(now);start.setHours(0,0,0,0);start.setDate(now.getDate()-now.getDay());let end=new Date(start);end.setDate(start.getDate()+7);return d>=start&&d<end}
function plannerTaskCard(t){return `<div class="task ${t.done?'done':''}"><input type="checkbox" aria-label="Complete ${t.name}" data-planner-task="${t.id}" ${t.done?'checked':''}><p><strong>${t.name}</strong><small>${t.scheduledAt?new Date(t.scheduledAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):t.time}${t.notify?' · reminder on':''}</small></p><span class="tag ${t.tag==='WORK'?'work':t.tag==='HEALTH'?'health':''}">${t.tag}</span><button class="remove-btn" data-planner-remove="${t.id}" aria-label="Remove ${t.name}" title="Remove task">×</button></div>`}
function renderPlanner(){let filtered=data.tasks.filter(t=>plannerFilter==='all'||(plannerFilter==='today'?dateIsToday(t.scheduledAt):dateIsThisWeek(t.scheduledAt)));$('#plannerTasks').innerHTML=filtered.length?filtered.map(plannerTaskCard).join(''):'<p class="muted empty-state">No tasks in this view yet.</p>';$$('[data-task-filter]').forEach(b=>b.classList.toggle('selected',b.dataset.taskFilter===plannerFilter));$$('[data-planner-task]').forEach(e=>e.onchange=()=>{let task=data.tasks.find(t=>t.id==e.dataset.plannerTask);task.done=e.checked;persist();refreshAll()});$$('[data-planner-remove]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this task?'))return;data.tasks=data.tasks.filter(t=>t.id!=b.dataset.plannerRemove);persist();refreshAll()})}
$$('[data-task-filter]').forEach(button=>button.onclick=()=>{plannerFilter=button.dataset.taskFilter;renderPlanner()});
function renderExpenses(){let today=new Date(),sameMonth=e=>{let d=new Date(e.date||today);return d.getFullYear()===today.getFullYear()&&d.getMonth()===today.getMonth()},month=data.expenses.filter(sameMonth),total=month.reduce((sum,e)=>sum+Number(e.amount||0),0),todayTotal=data.expenses.filter(e=>dateIsToday(e.date)).reduce((sum,e)=>sum+Number(e.amount||0),0),budget=12000;$('#spentStat').textContent=`₹${todayTotal.toLocaleString('en-IN')}`;$('#monthSpend').textContent=`₹${total.toLocaleString('en-IN')}`;$('#budgetBar').style.width=`${Math.min(100,Math.round(total/budget*100))}%`;$('#expenseList').innerHTML=data.expenses.length?data.expenses.slice(0,8).map(e=>`<div class="expense"><span class="expense-icon">${e.icon||'◈'}</span><p>${e.name}<small>${e.cat||'Other'} · ${e.date?new Date(e.date).toLocaleDateString('en-IN',{day:'numeric',month:'short'}):'Today'}</small></p><strong>− ₹${Number(e.amount||0).toLocaleString('en-IN')}</strong></div>`).join(''):'<p class="muted empty-state">No expenses recorded yet.</p>';let categories={};month.forEach(e=>categories[e.cat||'Other']=(categories[e.cat||'Other']||0)+Number(e.amount||0));$('#categoryBars').innerHTML=Object.entries(categories).length?Object.entries(categories).map(([name,value])=>`<div><span>${name}</span><i style="--width:${Math.min(100,value/Math.max(total,1)*100)}%"></i><b>₹${value.toLocaleString('en-IN')}</b></div>`).join(''):'<p class="muted empty-state">Add an expense to see your categories.</p>';let days=Array.from({length:7},(_,i)=>{let d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-6+i);return d}),values=days.map(d=>data.expenses.filter(e=>{let x=new Date(e.date||today);return x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth()&&x.getDate()===d.getDate()}).reduce((sum,e)=>sum+Number(e.amount||0),0)),max=Math.max(...values,1);$('#weekSpend').textContent=`₹${values.reduce((a,b)=>a+b,0).toLocaleString('en-IN')} total`;$('#spendingChart').innerHTML=days.map((d,i)=>`<div class="bar-day ${i===6?'today':''}"><i style="height:${Math.max(4,values[i]/max*110)}px"></i><b>${d.toLocaleDateString('en-IN',{weekday:'short'})}</b></div>`).join('')}
let oldRefreshAll=refreshAll;refreshAll=()=>{oldRefreshAll();renderPlanner()};
